TEXTS = {
    "en": {
        "app_title": "SplitZipper",
        "tab_archive": "Archive → .EXT",
        "tab_restore": ".EXT → Extract",
        "source_folder": "Source folder:",
        "dest_parts": "Destination for parts:",
        "encoded_folder": "Encoded parts folder:",
        "extract_to": "Extract to folder:",
        "run": "Run",
        "ready": "Ready.",
        "compressing": "Compressing…",
        "splitting": "Splitting…",
        "decoding": "Decoding…",
        "extracting": "Extracting…",
        "missing_source": "Please choose a source folder.",
        "missing_encoded": "Please choose the folder with .EXT files.",
        "done_parts": "Done. {count} parts saved to '{path}'.",
        "extracted_to": "Extracted to '{path}'.",
        "error": "Error: {msg}",
        "settings": "Settings",
        "chunk_size_label": "Chunk size (MiB)",
        "language_label": "Language",
        "extension_label": "File extension",
        "history_label": "Operation History",
        "language_en": "English",
        "language_ru": "Русский",
        "apply": "Apply",
        "cancel": "Cancel",
    },
    "ru": {
        "app_title": "SplitZipper",
        "tab_archive": "Архив → .EXT",
        "tab_restore": ".EXT → Распаковать",
        "source_folder": "Папка-источник:",
        "dest_parts": "Куда сохранить части:",
        "encoded_folder": "Папка с .EXT:",
        "extract_to": "Куда распаковать:",
        "run": "Запуск",
        "ready": "Готово.",
        "compressing": "Сжатие…",
        "splitting": "Разбиение…",
        "decoding": "Декодирование…",
        "extracting": "Распаковка…",
        "missing_source": "Пожалуйста, выберите папку-источник.",
        "missing_encoded": "Пожалуйста, выберите папку с .EXT файлами.",
        "done_parts": "Готово. {count} частей сохранено в '{path}'.",
        "extracted_to": "Распаковано в '{path}'.",
        "error": "Ошибка: {msg}",
        "settings": "Настройки",
        "chunk_size_label": "Размер чанка (МиБ)",
        "language_label": "Язык",
        "extension_label": "Расширение файлов",
        "history_label": "История операций",
        "language_en": "English",
        "language_ru": "Русский",
        "apply": "Применить",
        "cancel": "Отмена",
    },
}
